name: Propozycja funkcjonalności
description: Zaproponuj nową funkcjonalność
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Jaki problem rozwiązuje ta funkcjonalność?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proponowane rozwiązanie
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Obszar
      options:
        - Frontend
        - Backend
        - Inne
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Rozważane alternatywy
